global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # For self-signed certificates
    static_configs:
      - targets: ['fastapi_app:8000'] # Port for FastAPI server metrics

  - job_name: 'grpc'
    static_configs:
      - targets: ['calculator_server:8001']  # Port for gRPC server metrics

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']  # Port for Kafka metrics