# Use a lightweight Python base image
FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose port 50051 for gRPC server
EXPOSE 50051

# Start the gRPC server
CMD ["python", "server.py"]