
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: calculator_client
    environment:
      - GRPC_SERVER_URL=localhost:50051  # Ensure this matches your gRPC server URL

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: calculator_consumer
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017  # Ensure this matches your MongoDB URL
      - KAFKA_BROKER_URL=localhost:9092  # Ensure this matches your Kafka broker URL

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: calculator_server
    ports:
      - "50051:50051"
    environment:
      KAFKA_BROKER_URL: 'localhost:9092'  # Ensure this matches your Kafka broker URL