
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: calculator_client
    environment:
      - GRPC_SERVER_URL=server:50051  # Use the service name of the gRPC server
    depends_on:
      - server

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: calculator_consumer
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017  # Ensure this matches your MongoDB URL
      - KAFKA_BROKER_URL=kafka:9092  # Ensure this matches your Kafka broker URL

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: calculator_server
    ports:
      - "50051:50051"
    environment:
      - KAFKA_BROKER_URL=kafka:9092  # Ensure this matches your Kafka broker URL
      - FASTAPI_SERVER=fastapi:8000