# Use a lightweight Python base image
FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# Copy requirements file from the root of the project
COPY ../requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code from the calculator directory
COPY ../calculator/ .

# Start the Kafka consumer
CMD ["python", "calculator_consumer.py"]