{
 "title": "gRPC Metrics",
 "description": "gRPC service monitoring",
 "tags": [
  "gRPC",
  "go"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(grpc_server_started_total,cluster)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(grpc_server_started_total{cluster=\"$cluster\"},job)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Average handling time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (grpc_method) (rate(grpc_server_handling_seconds_sum[5m])) / \r\nsum by (grpc_method) (rate(grpc_server_handling_seconds_count[5m]))) *1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\", cluster=~\"$cluster\"}[$interval]))"
    }
   ]
  },
  {
   "title": "95th Percentile Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket[5m])) by (le, grpc_method)) * 1000\n",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$job\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{grpc_code=\"OK\"}[5m])) / sum(increase(grpc_server_handled_total[5m]))\n"
    }
   ]
  },
  { "title": "gRPC Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } }
 ]
}